apiVersion: v1
kind: Service
metadata:
  name: awesomewas
  namespace: awesome
spec:
  ports:
  - port: 8009
    name: ajp
    targetPort: 8009
  - port: 8080
    name: tomcat
    targetPort: 8080
  selector:
    tier: was